### ISSUE TITLE
EventStore 2.0.1 URL is dead and 3.0.0 version is downloaded instead

### ISSUE THREAD

**Issue by anderssonjohan** [haf/puppet-eventstore#4]
The URL http://download.geteventstore.com/binaries/eventstore-mono-2.0.1.tgz is dead if I try it in the browser. 
But when using the module with https://github.com/haf/vagrant-eventstore/blob/503cd63fc3f6ac69752cd8ef87a5b97533f9db51/run the box gets the 3.0.0 version instead.

I expected some URL to show up using --debug --verbose options to puppet, but I could not find any.

The first thing I noticed were that supervisord failed to start eventstore because the binary was missing.
In /opt/eventstore was something that I believe is the eventstore 3.0.0 release based on:
1. http://geteventstore.com/blog/20140903/event-store-3.0.0-static-linking-where-did-singlenode-go/
2. Grepping the new binary in the box:
   [vagrant@localhost eventstore]$ grep -F "3.0.0" clusternode
   Binary file clusternode matches
   [vagrant@localhost eventstore]$ grep -F "3.0.1" clusternode
   [vagrant@localhost eventstore]$

I have not tried the https://github.com/pawelkaczor/puppet-eventstore/commits/ver-3.0.0 branch in @pawelkaczor's fork yet but it seems that ppl are working on a module for eventstore 3.x?

**Comment by haf** [comment]
I've personally migrated to v3 through using the package which this module also supports: https://tc-oss.intelliplan.net/viewType.html?buildTypeId=RpmBrewing_EventStore_Build and https://packagecloud.io/haf/oss/, however, I haven't updated the invocation to eventstore. You can actually run eventstore just fine without any arguments, by just running `clusternode`.

I didn't know the url was dead, it's a shame they get unpublished. The vagrant example is also for v2.0 and when I worked on it a month ago it was working just fine. How frustrating...

I've been experimenting locally with v3, but haven't got it in production yet, so I haven't updated this module. It should be just to call `clusternode` instead and re-work the options. I'll merge any PRs sent my way :)

**Comment by anderssonjohan** [comment]
> It should be just to call clusternode instead and re-work the options

Nah, also tried the run-node.sh script - bundled with eventstore 3.x - but without luck.
Maybe this error is because of the choice of centos box given by the Vagrantfile?

```
 $ vagrant ssh -c "sudo supervisorctl tail -120 eventstore stdout"
 /opt/eventstore/clusternode: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /opt/eventstore/clusternode)
```
